name: DeepEval Test Run Example

# This is an example YML file to show the results of a DeepEval test run to a PR

on:
  pull_request:

jobs:
  create-pip-link-comment:
    runs-on: ubuntu-latest
    permissions: write-all
    name: pip link
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install deepeval
        run: pip install deepeval

      
      - name: Run Test
        run: |
          echo 'var<<EOF' >> $GITHUB_ENV
          echo $(deepeval test run tests/test_quickstart.py) >> $GITHUB_ENV
          echo 'EOF' >> $GITHUB_ENV
          # deepeval test run tests/test_quickstart.py | tr '\n' ' ' > output.txt
          # EOF=$(cat output.txt)
          # echo "test_result=$EOF" >> "$GITHUB_ENV"
          # echo "$EOF" >> "$GITHUB_ENV"

      - name: Comment PR
        uses: marocchino/sticky-pull-request-comment@v2
        with:
          hide_and_recreate: true
          hide_classify: "OUTDATED"
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          message: |
            Thanks for running DeepEval 😎
            Results:
            ```
            ${{ env.test_result }}
            ```
