name: DeepEval Test Run Example

# This is an example YML file to show the results of a DeepEval test run to a PR

on:
  pull_request:

jobs:
  create-pip-link-comment:
    runs-on: ubuntu-latest
    permissions: write-all
    name: pip link
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install deepeval
        run: pip install deepeval

      - name: Echo Command
        id: echo
        run: |
          PROGRAM_OUTPUT=$(deepeval test run tests/test_quickstart.py)
          echo "OUTPUT=$PROGRAM_OUTPUT" >> $GITHUB_ENV
        
      - name: Using the previously defined environment variable
        run: |
          echo ${{ env.OUTPUT }}

      # - name: Comment PR
      #   uses: marocchino/sticky-pull-request-comment@v2
      #   with:
      #     hide_and_recreate: true
      #     hide_classify: "OUTDATED"
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      #     message: |
      #       Thanks for the PR! Going to review and merge soon 😉
      #       Just before that though can you please test the installation with the command below? 😎
      #       ```
      #       ${{ env.OUTPUT }}
      #       ```
