name: Run pytest in matrix

on: push

jobs:
  examples:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10"]
    steps:
      - uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Cache pip dependencies
        uses: actions/cache@v2
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install dependencies
        env:
          python-version: ${{ matrix.python-version }}
        run: |
          python -c "import sys; print(sys.version)"
          python -m pip install --upgrade pip
          python -m pip install -r requirements.txt ragas
          python -m pip install . pytest-rerunfailures pytest-asyncio

      - name: Run Unit Tests (pytest)
        env:
          python-version: ${{ matrix.python-version }}
        run: |
          python tests/test_without_pytest.py
          deepeval test run -x tests

