name: Run pytest in matrix

on:
  pull_request:
    paths:
      - "tests/**" # Adjust the path to match your test files' location

jobs:
  examples:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.9"]
    steps:
      - uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        env:
          python-version: ${{ matrix.python-version }}
        run: |
          python -c "import sys; print(sys.version)"
          python -m pip install --upgrade pip
          python -m pip install -r requirements.txt
          python -m pip install . pytest-rerunfailures pytest-asyncio

      - name: Discover test files
        id: discover-tests
        run: |
          TEST_FILES=$(find tests/ -name "test_*.py")
          echo "::set-output name=test_files::$TEST_FILES"

      - name: Run Unit Tests (pytest)
        env:
          python-version: ${{ matrix.python-version }}
          CONFIDENT_AI_API_KEY: ${{ secrets.API_KEY_ENV }}
          CONFIDENT_AI_IMP_ID: ${{ secrets.CONFIDENT_AI_IMP_ID }}
        run: |
          python -c "import sys; print(sys.version)"
          for TEST_FILE in ${{ steps.discover-tests.outputs.test_files }}; do
            python -m pytest -x $TEST_FILE
          done
