name: Run pytest in matrix

on: 
  push:
  pull_request:

jobs:
  examples:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.7", "3.9"]
    steps:
      - uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Get pip cache dir
        id: pip-cache
        run: echo "::set-output name=dir::$(pip cache dir)"

      - name: Cache pip dependencies
        uses: actions/cache@v2
        with:
          path: ${{ steps.pip-cache.outputs.dir }}
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install dependencies
        env:
          python-version: ${{ matrix.python-version }}
        run: |
          python -c "import sys; print(sys.version)"
          python -m pip install --upgrade pip
          python -m pip install -r requirements.txt ragas
          python -m pip install . pytest-rerunfailures pytest-asyncio

      - name: Run Unit Tests (pytest)
        env:
          python-version: ${{ matrix.python-version }}
          CONFIDENT_AI_API_KEY: ${{ secrets.API_KEY_ENV }}
          CONFIDENT_AI_IMP_ID: ${{ secrets.CONFIDENT_AI_IMP_ID }}
        run: |
          deepeval test run -x tests


